db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: Qwerty@12345
  volumes:
    - /home/ubuntu/Java-Mysql-Simple-Login-Web-application/mysql/sample.sql:/docker-entrypoint-initdb.d/init.sql
    - /sql:/var/lib/mysql

web:
  build: ./
  ports:
    - "80:8080"
  links:
    - db


